#!/usr/bin/env bash
echo -e "\n"
echo "       MM   MMM  MMM MMMMMMM MM      MMMMMM  ,MMMMMM   MMM  +MMM MMMMMMM        "
echo "       MMM MMMM  MM  MM      MM     MMN  ~~ 7MM   MMM  MMMM~MMMM MM             "
echo "        MM MMMMMMM,  MMMMMM  MM     MM      MMM    MM  MMMMMMMMM MMMMMM=        "
echo "        MMMMM MMMM   MM      MM     MM?     NMM   MMM  MM MM MMM MM             "
echo "         MMM  MMM    MMMMMMM MMMMMM  MMMMMM  MMMMMMM   MM    MMM MMMMMMM        "
echo "                                                                                "
echo "                                                                                "
echo "    MMM   MMM MMMMMMM         MMMMMN   MMM   MM MMM    MMM    MM~    MMMMM,     "
echo "    MMMM MMMM MMM?MMMM        MMMMMMMD MMM   MM MMMM, MMMM   MMMM   MMM ,M      "
echo "    MMMMMMMMM MMM  ?MM        MM    MM MMM   MM MMMMMMMMMM  MMMMMM  :MMMM7      "
echo "    MM MMN MM MMMMMMM         MM   ~MM MMM   MM MMM MM MMM  MMMMMM~    MMMM     "
echo "    MM  N  MM MMM MMM  MM     MMMMMMM, ,MMMMMMM MMM    MMM MMMMMMMM MMMMMMM     "
echo "    MM     MM MMM  NMM MM     MMMMM      MMMM   MMM    MMMDMM    MMM  MMMM      "
echo -e "\n"
