#!/bin/zsh
echo -e "\n"
echo "       MM   MMM  MM= MMMMMMM MM      MMMMMM  ,MMMMMM   MMM  +MMM MMMMMMM        "
echo "       OMM MMMM  MM  MM      MM     MMN  ~~ 7MM   MMM  MMMM~MMMM MM             "
echo "        MM MMMMMMM,  MMMMMM  MM     MM      MMM    MM  MMMMMMMMM MMMMMM=        "
echo "        IMMMI MMMM   MM      MM     MM?     NMM   OMM  MM MM MMM MM             "
echo "         MMM  8MM    MMMMMMM MMMMMM  MMMMMM  MMMMMMM   MM    MMM MMMMMMM        "
echo "                                                                                "
echo "                                                                                "
echo "    MMM   MMM OMMMMMO         MMMMMN   MMM   MM OMM    MMI    MM~    $MMMM,     "
echo "    MMMM MMMM OMM?IMMM        MMOZMMMD MMM   MM OMMM, MMMI   MMMM   MMM ,M      "
echo "    MMMMMMMMM OMM  ?MM        MM    MM MMM   MM OMMMMMMMMI  8MMMMM  :MMMM7      "
echo "    MM MMN MM OMMMMMM         MM   ~MM MMM   MM OMM MM MMI  MMIIMM~    MMMM     "
echo "    MM  N  MM OMM MMM  MM     MMMMMMM, ,MMMMMMM OMM    MMI MMMMMMMM 8MM88MM     "
echo "    MM     MM 8MM  NMM MM     MMMMM      MMMM   OMM    MMIDMM    MMM  MMMM      "
echo -e "\n"
